package org.example;
/*
 * This source file was generated by the Gradle 'init' task
 */


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class ExampleTest {
    @Test void testSumar() {
        Example example = new Example();
        int result = example.sumar(2, 4);
        assertEquals(6, result);
    }

    @Test void testSumar2() {
        Example example = new Example();
        int result = example.sumar(2, 4);
        //Verifica booleanos
        assertTrue(result>2);
        assertFalse(result<2);
        }
@Test void testSumar4() {
        Example example = new Example();
        int result = example.sumar(2, 4);
        //Verifica tipo de objeto
        assertInstanceOf(Integer.class, result);
        }

            @Test void testSumar5() {
        Example example = new Example();
        int result = example.sumar(2, 4);
        //Verifica excepciones
        try {
            assertNotNull(result);
        } catch (Exception e) {
            if (e instanceof NullPointerException) {
                // Handle the exception
                System.out.println("NullPointerException caught");
            } else {
                // Handle other exceptions
                System.out.println("Other exception caught: " + e.getMessage());
            }
        }
    }
}
